### ISSUE TITLE
A green pane overlaps and remains on the screen

### ISSUE THREAD

**Issue by plashenkov** [ptmt/react-native-macos#193]
### Description

I've just installed React Native macOS and tried to start a very first project:
```
yarn global add react-native-macos-cli
react-native-macos init MyProject
cd MyProject
react-native-macos run-macos
```

After that I can see a green pane overlapping a bottom of my screen. It does not want to disappear. When I press Cmd+R, a new one pane overlaps previous. When I press Cmd+R again, a third one overlaps previous two. Here are the screenshots:

http://take.ms/Ckcng
http://take.ms/FxBvz
http://take.ms/zZnIp

* React Native version: react-native-macos-cli: 2.0.1, react-native-macos: 0.16.1
* Platform: macOS
* Development Operating System: macOS 10.13.4
* Dev tools: Xcode 9.3 (9E145)

**Comment by SeniorZhai** [comment]
+1

**Comment by ptmt** [comment]
Hopefully fixed in 0.18. Let me know if it persists

**Comment by shirakaba** [comment]
Still an issue in `0.18.0-alpha-3`:

<img width="1280" alt="screen shot 2018-07-04 at 00 35 37" src="https://user-images.githubusercontent.com/14055146/42249246-3da13e02-7f22-11e8-8cf2-09b316f9c88b.png">
